notifications:
  email: false

sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4'
  - '5'

script:
  - gulp

after_success:
  - npm i coveralls
  - cat coverage/lcov.info | node_modules/.bin/coveralls
